modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"

[[mods]]
modId="axe_or_ex"
version="1.0.0"
displayName="Axe Or Ex"
authors="Emtypyie"
description='''
Adds throwable axes.
'''

[[dependencies.axe_or_ex]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.axe_or_ex]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
